spring:
  application:
    name: backend

  messages:
    basename: messages/messages-error
    encoding: UTF-8
    cache-duration: 3600

  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    generate-ddl: ${GENERATE_DDL}
    hibernate:
      ddl-auto: ${DDL_AUTO}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

jwt:
  secret: ${JWT_SECRET}
  access:
    expiration: 3600 # 1시간
    header: ${JWT_ACCESS_HEADER}
  refresh:
    expiration: ${JWT_REFRESH_EXPIRATION}
    cookie: ${JWT_REFRESH_COOKIE}

oauth:
  kakao:
    token_url: "https://kauth.kakao.com/oauth/token"
    user_url: "https://kapi.kakao.com/v2/user/me"
    grant_type: authorization_code
    client_id: ${KAKAO_CLIENT_ID} #kakao client id
    client_secret: #kakao secret key
    redirect_uri: ${KAKAO_REDIRECT_URI} #kakao redirect uri
  google:
    token_url: "https://oauth2.googleapis.com/token"
    user_url: "https://www.googleapis.com/oauth2/v3/userinfo"
    grant_type: authorization_code
    client_id: ${GOOGLE_CLIENT_ID} #google client id
    client_secret: ${GOOGLE_CLIENT_SECRET} #google secret key
    redirect_uri: ${GOOGLE_REDIRECT_URI} #google redirect uri
  naver:
    token_url: "https://nid.naver.com/oauth2.0/token"
    user_url: "https://openapi.naver.com/v1/nid/me"
    grant_type: authorization_code
    client_id: ${NAVER_CLIENT_ID}
    client_secret: ${NAVER_CLIENT_SECRET}
    redirect_uri: ${NAVER_REDIRECT_URI}

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ap-northeast-2
    s3:
      bucket: ${AWS_S3_BUCKET}