name: ğŸš€ Deploy workflow on test environment

on:
  push:
    branches: ['release/**', 'release']

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # ì½”ë“œ ë³µì‚¬
      - name: check out the repo
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
        
          echo "KAKAO_CLIENT_ID=${{secrets.KAKAO_CLIENT_ID}}" >> .env
          echo "KAKAO_REDIRECT_URI=${{secrets.KAKAO_REDIRECT_URI}}" >> .env
          
          echo "GOOGLE_CLIENT_ID=${{secrets.GOOGLE_CLIENT_ID}}" >> .env
          echo "GOOGLE_CLIENT_SECRET=${{secrets.GOOGLE_CLIENT_SECRET}}" >> .env
          echo "GOOGLE_REDIRECT_URI=${{secrets.GOOGLE_REDIRECT_URI}}" >> .env
          
          echo "NAVER_CLIENT_ID=${{secrets.NAVER_CLIENT_ID}}" >> .env
          echo "NAVER_CLIENT_SECRET=${{secrets.NAVER_CLIENT_SECRET}}" >> .env
          echo "NAVER_REDIRECT_URI=${{secrets.NAVER_REDIRECT_URI}}" >> .env
          
          echo "JWT_SECRET=${{secrets.JWT_SECRET}}" >> .env
          echo "JWT_ACCESS_EXPIRATION=${{secrets.JWT_ACCESS_EXPIRATION}}" >> .env
          echo "JWT_ACCESS_HEADER=${{secrets.JWT_ACCESS_HEADER}}" >> .env
          echo "JWT_REFRESH_EXPIRATION=${{secrets.JWT_REFRESH_EXPIRATION}}" >> .env
          echo "JWT_REFRESH_COOKIE=${{secrets.JWT_REFRESH_COOKIE}}" >> .env
          
          echo "DATASOURCE_URL=${{secrets.DATASOURCE_RELEASE_URL}}" >> .env
          echo "GENERATE_DDL=${{secrets.GENERATE_DDL}}" >> .env
          echo "DATABASE_USERNAME=${{secrets.DATABASE_USERNAME}}" >> .env
          echo "DATABASE_PASSWORD=${{secrets.DATABASE_PASSWORD}}" >> .env
          
          echo "DDL_AUTO=${{secrets.DDL_AUTH}}" >> .env
          
          echo "REDIS_HOST=${{secrets.REDIS_RELEASE_HOST}}" >> .env
          echo "REDIS_PORT=${{secrets.REDIS_PORT}}" >> .env
          
          echo "AWS_ACCESS_KEY=${{secrets.AWS_ACCESS_KEY_ID}}" >> .env
          echo "AWS_SECRET_KEY=${{secrets.AWS_SECRET_ACCESS_KEY}}" >> .env
          echo "AWS_S3_BUCKET=${{secrets.AWS_S3_BUCKET}}" >> .env

      # Gradle í…ŒìŠ¤íŠ¸ ì‹¤í–‰ (í…ŒìŠ¤íŠ¸ê°€ ì‹¤íŒ¨í•˜ë©´ ì›Œí¬í”Œë¡œìš°ê°€ ì¤‘ë‹¨ë¨)
      - name: Run tests
        run: ./gradlew test --no-daemon

      # ë„ì»¤ ë¡œê·¸ì¸
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Docker ì´ë¯¸ì§€ ë¹Œë“œ
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/mos:${{ github.sha }} .
          docker tag ${{ secrets.DOCKER_USERNAME }}/mos:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/mos:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/mos:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/mos:latest 

      # AWS ìê²© ì¦ëª…
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      # ë°°í¬ ì‹œì‘
      - name: ğŸš€ Deploy to EC2 with CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name mos-deployer \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --deployment-group-name mos-release \
            --github-location repository=${{ github.repository }},commitId=${{ github.sha }} 
